[workspace]
authors = ["igamenovoer <igamenovoer@xx.com>"]
channels = ["conda-forge"]
name = "sqpr-reading-notes"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.2,<3.15"

[pypi-dependencies]
scipy = ">=1.16.3, <2"
attrs = ">=25.4.0, <26"
omegaconf = ">=2.3.0, <3"
mdutils = ">=1.8.1, <2"
pymupdf = ">=1.26.6, <2"
